### ISSUE TITLE
about Prefix

### ISSUE THREAD

**Issue by pkptzx** [dylni/normpath#18]
Because I need to use low-level file operations, I require a standardized `Component::Prefix` that is returned.

```rust
    let path = PathBuf::from_str("C:\\Users\\").unwrap();
    let apath = path.canonicalize().unwrap();
    println!("{}",apath.as_os_str().to_str().unwrap());
    println!("{:?}", apath.components().filter(|comp| match comp {Component::Prefix(s)=>true,
        _=>false}).collect::<Vec<Component>>());
     //[Prefix(PrefixComponent { raw: "\\\\?\\C:", parsed: VerbatimDisk(67) })]
   
    let npath = path.normalize().unwrap();
    println!("{}",npath.as_os_str().to_str().unwrap());
    println!("{:?}", npath.components().filter(|comp| match comp {Component::Prefix(s)=>true,
   _=>false}).collect::<Vec<Component>>());
   //[Prefix(PrefixComponent { raw: "C:", parsed: Disk(67) })]
```
I expect the return result to be consistent with that of the `canonicalize` function, i.e., either `\\.\C:` or `\\?\C:`

**Comment by pkptzx** [comment]
MSDN:
https://learn.microsoft.com/zh-cn/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN

**Comment by dylni** [comment]
This is expected. `canonicalize` and `normalize` are different methods with different behavior. `canonicalize` will prefer returning verbatim paths even if not needed, but `normalize` will avoid them when the input path is not a verbatim path. Which method to use depends on which type of path you need, but the results will very frequently be different.

This is further explained in the documentation for [`PathExt::normalize`](https://docs.rs/normpath/latest/normpath/trait.PathExt.html#tymethod.normalize).
