### ISSUE TITLE
Normalise MSDOS short paths

### ISSUE THREAD

**Issue by caesay** [dylni/normpath#19]
It would be really slick if this library could also use `GetLongPathNameW` to expand MSDOS short paths. For example, confronted with the following path I need to use `.normalize()` followed by GetLongPathNameW in my own code to actually get a normalized path:

> C:\Users\RUNNER~1\AppData\Local\Temp\.tmpN5xnH8

Since `.normalize()` already requires the file/path to exist, it would make sense for it to call this. It will not work for the `_virtually()` variant.

**Comment by dylni** [comment]
This is a great idea. The code on the default branch has been updated to include this change, and it will be published as part of 1.3.0. Let me know if you are able to test it before that point.

**Comment by dylni** [comment]
This has been published as version 1.3.0.
